#stategy params
strategy_name: CWRStar
patterns_per_exp: 256
minibatch_size:  128

#model and training params
model_name: wide_VGG9
num_classes: 200
lr: 0.001
hs: 250
epochs: 70

#scenario params
scenario: split_imagenet
resized: not
balanced: not
number_of_samples_per_class: 500
scenario_type: task_incremental


num_class_from_imagenet: 10
num_experiences: 40