#stategy params
strategy_name: GenerativeReplay
patterns_per_exp: 256
minibatch_size:  128
replay_mem_size: 200

#model and training params
model_name: EfficientNet_NotPretrained
num_classes: 60
lr: 0.001
momentum: 0.9
hs: 250
epochs: 50

#scenario params
scenario: short_mnist_omniglot_fmnist_svhn_cifar10_imagenet
resized: resized
balanced: balanced
number_of_samples_per_class: 500
scenario_type: class_incremental


num_class_from_imagenet: 10
num_experiences: 5