#stategy params
strategy_name: SI
patterns_per_exp: 256
minibatch_size:  128
si_lambda: 1
si_eps: 0.001

#model and training params
model_name: wide_VGG9
num_classes: 250
lr: 0.001
hs: 250
epochs: 50

#scenario params
scenario: imagenet_to_mnist_long
num_class_from_imagenet: 200
num_experiences: 5
scenario_type: class_incremental